#define STORYTELLER_POLARITY_NEGATIVE "negative"
#define STORYTELLER_POLARITY_POSITIVE "positive"

#define STORYTELLER_CONTEXT_ROUNDSTART "roundstart"
#define STORYTELLER_CONTEXT_MIDROUND "midround"
#define STORYTELLER_CONTEXT_LATEJOIN "latejoin"

#define STORYTELLER_ROUND_MODE_DYNAMIC "dynamic"
#define STORYTELLER_ROUND_MODE_EXTENDED "extended"
#define STORYTELLER_MODE_HISTORY_FILE "data/storyteller_mode_history.json"
#define STORYTELLER_MODE_ALTERNATION_LOW_POP_THRESHOLD 20
#define STORYTELLER_MODE_ALTERNATION_HIGH_POP_THRESHOLD 50

#define STORYTELLER_NEED_FOOD_SHORTAGE "food_shortage"
#define STORYTELLER_NEED_ENGINEERING_REPAIRS "engineering_repair_crisis"
#define STORYTELLER_NEED_MATERIAL_SHORTAGE "material_shortage"
#define STORYTELLER_NEED_MEDICAL_SURGE "medical_surge"
#define STORYTELLER_NEED_SECURITY_STRAIN "security_strain"
#define STORYTELLER_NEED_SCIENCE_SHORTAGE "science_shortage"
#define STORYTELLER_NEED_JANITORIAL_OVERLOAD "janitorial_overload"

#define STORYTELLER_DEFAULT_HEAVY_SCAN_INTERVAL (3 MINUTES)
#define STORYTELLER_DEFAULT_RECENT_WINDOW (15 MINUTES)
#define STORYTELLER_DEFAULT_FATIGUE_LOCK (4 MINUTES)
#define STORYTELLER_DEFAULT_FAMILY_COOLDOWN (10 MINUTES)
#define STORYTELLER_DEFAULT_LATEJOIN_HOSTILE_LOCK (15 MINUTES)
#define STORYTELLER_DEFAULT_NEGATIVE_ROUNDSTART_DELAY_MIN (10 MINUTES)
#define STORYTELLER_DEFAULT_NEGATIVE_ROUNDSTART_DELAY_MAX (15 MINUTES)
#define STORYTELLER_DEFAULT_POSITIVE_ROUNDSTART_DELAY_MIN (15 MINUTES)
#define STORYTELLER_DEFAULT_POSITIVE_ROUNDSTART_DELAY_MAX (30 MINUTES)
#define STORYTELLER_DEFAULT_LATEJOIN_ROUNDSTART_LOCK_MIN (30 MINUTES)
#define STORYTELLER_DEFAULT_LATEJOIN_ROUNDSTART_LOCK_MAX (60 MINUTES)
#define STORYTELLER_DEFAULT_NEGATIVE_INTERVAL_MIN (10 MINUTES)
#define STORYTELLER_DEFAULT_NEGATIVE_INTERVAL_MAX (30 MINUTES)
#define STORYTELLER_DEFAULT_POSITIVE_INTERVAL_MIN (10 MINUTES)
#define STORYTELLER_DEFAULT_POSITIVE_INTERVAL_MAX (15 MINUTES)
#define STORYTELLER_DEFAULT_ACTION_QUEUE_DELAY (5 MINUTES)
#define STORYTELLER_DEFAULT_SETUP_PREP_DURATION (1 MINUTES)

#define STORYTELLER_DYNAMIC_TIER_MIN 0
#define STORYTELLER_DYNAMIC_TIER_MAX 4

#define STORYTELLER_DECISION_HISTORY_MAX 20

#define STORYTELLER_QUEUE_SOURCE_STORYTELLER "storyteller"
#define STORYTELLER_QUEUE_SOURCE_ADMIN "admin"

#define STORYTELLER_MOD_CARGO_SALES "cargo_sales"
#define STORYTELLER_MOD_CARGO_PROCESSING "cargo_processing"
#define STORYTELLER_MOD_SCIENCE_PATENTS "science_patents"
#define STORYTELLER_MOD_MEDICAL_REPLICATION "medical_replication"
#define STORYTELLER_MOD_BOTANY_GROWTH "botany_growth"
#define STORYTELLER_MOD_ENGINEERING_POWER "engineering_power"
